[build]
  publish = "public"
  functions = "netlify/functions"

[functions.environment]
  API_KEY = "iAMKOj6S4357Lc1GocK6sa5NKstfzK6N1zMjzSM1"

[[redirects]]
  from = "/parse-resume"
  to = "/.netlify/functions/parse-resume"
  status = 200
